#!/bin/sh
commit_msg=$(cat "$1")
if ! echo "$commit_msg" | grep -Eq "^(feat|fix|chore|docs|style|refactor|test|ci|build|add|update|remove|merge|address)(\(.+\))? .+"; then
  echo "❌ Invalid commit message format!"
  echo "✅ Expected: 'feat|fix|chore|docs|style|refactor|test|ci|build|add|update|remove|merge|address: message'"
  exit 1
fi